version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:23.08.3
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=${APP_URL:-http://localhost:6875}
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${DOCS_MARIADB_PASSWORD}
      - DB_DATABASE=bookstackapp
    volumes:
      - ~/data/bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb:10.11.5
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${DOCS_MARIADB_ROOT_PASSWORD}
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${DOCS_MARIADB_PASSWORD}
    volumes:
      - ~/data/bookstack_db_data:/config
    restart: unless-stopped
